esphome:
    name: ampmeter

esp32:
    board: nodemcu-32s
    framework:
      type: esp-idf

web_server:
  port: 80 # integer value

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:
  - platform: esphome
    password: !secret ota_password

# Example configuration entry
uart:
  rx_pin: GPIO17
  tx_pin: GPIO16
  baud_rate: 9600

modbus:

sensor:
  - platform: pzemac
    current:
      name: "PZEM-004T V3 Current"
    voltage:
      name: "PZEM-004T V3 Voltage"
    energy:
      name: "PZEM-004T V3 Energy"
    power:
      name: "PZEM-004T V3 Power"
    frequency:
      name: "PZEM-004T V3 Frequency"
    power_factor:
      name: "PZEM-004T V3 Power Factor"
    update_interval: 30s

switch:
  - platform: gpio
    pin: GPIO4
    name: "Heater"
