esphome:
  name: crawlspace

esp8266:
  board: esp01_1m

# Enable logging
logger:

api:
    encryption:
        key: !secret api_encryption_key
        
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO2
    temperature:
      name: "Crawl space Temperature"
    humidity:
      name: "Crawl space Humidity"
    update_interval: 60s
    
