esphome:
  name: temp01

esp32:
  board: esp32doit-devkit-v1


time:
  - platform: homeassistant
    id: hass_time

web_server:
  port: 80

# Enable logging
logger:

api:
    encryption:
        key: !secret api_encryption_key

ota:
  platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: restart
    name: "temp01 Restart"

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO4
    temperature:
      id: temp01_temperature
      name: "temp01 Temperature"
      device_class: temperature
    humidity:
      id: temp01_humidity
      name: "temp01 Humidity"
      device_class: humidity
      accuracy_decimals: 1
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    entity_category: "diagnostic"
    device_class: duration
    update_interval: 60s
  - platform: wifi_signal
    name: "RSSI"
    id: wifi_rssi
    entity_category: "diagnostic"
    update_interval: 60s    
