esphome:
  name: livingroom

esp8266:
  board: esp01_1m

# Enable logging
logger:

api:
    encryption:
        key: p7v03v277rWr60OOYMEjrWzLD0asq08FQRFNnAGXX8k=

ota:
  password: !secret ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s