substitutions:
  # Modify variables based on your settings
  hostname: "switch01"
  devicename: switch01

esphome:
  name: switch01

esp32:
  board: esp32doit-devkit-v1


# Enable logging
logger:
  level: INFO

packages:
  common_system: !include common_system.yaml
  common_sensors: !include common_sensors.yaml

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: gpio
    pin: GPIO2
    name: "Switch"
    restore_mode: ALWAYS_ON
